/**
 * Migrations — AGENTS.md / config.toml generators
 *
 * convertSkillSyntax, generateAgentsMdFromParsed, convertSettingsToToml,
 * generateConfigTomlFromParsed. Extracted verbatim from
 * migrations/index.ts (lines 518-841) during campaign-2 wave 6 (W212).
 * index.ts stays the barrel.
 */

import type { ParsedClaudeMd } from './types.js';

export function convertSkillSyntax(content: string): string {
  // Convert /skill-name to $skill-name, but avoid path-like patterns
  return content.replace(/(?<![a-zA-Z0-9_./])\/([a-z][a-z0-9-]*)(?![a-zA-Z0-9_./])/g, (match, skillName) => {
    // Skip common directory names
    const skipPatterns = ['src', 'dist', 'docs', 'tests', 'config', 'scripts', 'examples', 'node_modules', 'workspaces', 'data', 'logs', 'tmp', 'var', 'etc', 'usr', 'bin', 'lib'];
    if (skipPatterns.includes(skillName)) {
      return match;
    }
    return `$${skillName}`;
  });
}

/**
 * Generate AGENTS.md content from parsed CLAUDE.md
 */
export function generateAgentsMdFromParsed(parsed: ParsedClaudeMd): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${parsed.title || 'Project Agent Guide'}`);
  lines.push('');
  lines.push('> Migrated from CLAUDE.md by @claude-flow/codex');
  lines.push('');

  // Project Overview
  lines.push('## Project Overview');
  lines.push('');
  if (parsed.settings.techStack) {
    lines.push(`**Tech Stack**: ${parsed.settings.techStack}`);
  }
  lines.push('');

  // Quick Start
  lines.push('## Setup');
  lines.push('');
  if (parsed.settings.buildCommand) {
    lines.push('### Build');
    lines.push('```bash');
    lines.push(parsed.settings.buildCommand);
    lines.push('```');
    lines.push('');
  }
  if (parsed.settings.testCommand) {
    lines.push('### Test');
    lines.push('```bash');
    lines.push(parsed.settings.testCommand);
    lines.push('```');
    lines.push('');
  }
  if (parsed.settings.devCommand) {
    lines.push('### Development');
    lines.push('```bash');
    lines.push(parsed.settings.devCommand);
    lines.push('```');
    lines.push('');
  }

  // Code Standards
  lines.push('## Code Standards');
  lines.push('');
  lines.push('- Files under 500 lines');
  lines.push('- No hardcoded secrets');
  lines.push('- Input validation at boundaries');
  lines.push('- Typed interfaces for public APIs');
  lines.push('');

  // Skills
  if (parsed.skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    lines.push('| Skill | Original Syntax |');
    lines.push('|-------|-----------------|');
    for (const skill of parsed.skills) {
      const codexSyntax = `$${skill.name}`;
      const originalSyntax = skill.syntax === 'slash' ? `/${skill.name}` : `$${skill.name}`;
      lines.push(`| \`${codexSyntax}\` | \`${originalSyntax}\` |`);
    }
    lines.push('');
  }

  // Security
  lines.push('## Security');
  lines.push('');
  if (parsed.customInstructions.length > 0) {
    for (const rule of parsed.customInstructions.slice(0, 10)) {
      lines.push(`- ${rule}`);
    }
  } else {
    lines.push('- NEVER commit secrets or credentials');
    lines.push('- Validate all user inputs');
    lines.push('- Prevent directory traversal attacks');
  }
  lines.push('');

  // Hooks (as reference)
  if (parsed.hooks.length > 0) {
    lines.push('## Automation Hooks');
    lines.push('');
    lines.push('The following hooks were detected in the original configuration:');
    lines.push('');
    for (const hook of parsed.hooks) {
      lines.push(`- \`${hook}\``);
    }
    lines.push('');
    lines.push('> Note: Codex uses scheduled Automations instead of event-driven hooks.');
    lines.push('');
  }

  // MCP Servers
  if (parsed.mcpServers.length > 0) {
    lines.push('## MCP Servers');
    lines.push('');
    lines.push('Configure in config.toml:');
    lines.push('');
    for (const server of parsed.mcpServers) {
      lines.push(`- **${server.name}**: \`${server.command} ${(server.args || []).join(' ')}\``);
    }
    lines.push('');
  }

  // Migration notes
  if (parsed.warnings.length > 0) {
    lines.push('## Migration Notes');
    lines.push('');
    for (const warning of parsed.warnings) {
      lines.push(`- ${warning}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Convert settings.json to config.toml format
 */
export function convertSettingsToToml(settings: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push('# Migrated from settings.json');
  lines.push('# Generated by @claude-flow/codex');
  lines.push('');

  // Model
  if (settings.model) {
    lines.push(`model = "${settings.model}"`);
  } else {
    lines.push('model = "gpt-5.3-codex"');
  }
  lines.push('');

  // Permissions mapping
  if (settings.permissions) {
    const perms = settings.permissions as Record<string, unknown>;
    if (perms.autoApprove === true) {
      lines.push('approval_policy = "never"');
      lines.push('sandbox_mode = "danger-full-access"');
    } else if (perms.autoApprove === 'read-only') {
      lines.push('approval_policy = "on-request"');
      lines.push('sandbox_mode = "read-only"');
    } else {
      lines.push('approval_policy = "on-request"');
      lines.push('sandbox_mode = "workspace-write"');
    }
  } else {
    lines.push('approval_policy = "on-request"');
    lines.push('sandbox_mode = "workspace-write"');
  }
  lines.push('');

  // Web search
  if (settings.webSearch !== undefined) {
    const mode = settings.webSearch === true ? 'live' : settings.webSearch === false ? 'disabled' : 'cached';
    lines.push(`web_search = "${mode}"`);
  } else {
    lines.push('web_search = "cached"');
  }
  lines.push('');

  // Features
  lines.push('[features]');
  lines.push('child_agents_md = true');
  lines.push('shell_snapshot = true');
  lines.push('request_rule = true');
  lines.push('');

  // MCP servers
  if (settings.mcpServers && typeof settings.mcpServers === 'object') {
    for (const [name, config] of Object.entries(settings.mcpServers as Record<string, unknown>)) {
      const mcpConfig = config as { command?: string; args?: string[]; env?: Record<string, string> };
      lines.push(`[mcp_servers.${name}]`);
      if (mcpConfig.command) {
        lines.push(`command = "${mcpConfig.command}"`);
      }
      if (mcpConfig.args && mcpConfig.args.length > 0) {
        const argsStr = mcpConfig.args.map((a) => `"${a}"`).join(', ');
        lines.push(`args = [${argsStr}]`);
      }
      lines.push('enabled = true');

      if (mcpConfig.env && Object.keys(mcpConfig.env).length > 0) {
        lines.push('');
        lines.push(`[mcp_servers.${name}.env]`);
        for (const [key, value] of Object.entries(mcpConfig.env)) {
          lines.push(`${key} = "${value}"`);
        }
      }
      lines.push('');
    }
  } else {
    // Add default claude-flow server
    lines.push('[mcp_servers.ruflo]');
    lines.push('command = "npx"');
    lines.push('args = ["-y", "ruflo@latest", "mcp", "start"]');
    lines.push('enabled = true');
    lines.push('');
  }

  // History
  lines.push('[history]');
  lines.push('persistence = "save-all"');
  lines.push('');

  // Profiles
  lines.push('# Development profile');
  lines.push('[profiles.dev]');
  lines.push('approval_policy = "never"');
  lines.push('sandbox_mode = "danger-full-access"');
  lines.push('');

  lines.push('# Safe profile');
  lines.push('[profiles.safe]');
  lines.push('approval_policy = "untrusted"');
  lines.push('sandbox_mode = "read-only"');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate config.toml from parsed CLAUDE.md
 */
export function generateConfigTomlFromParsed(parsed: ParsedClaudeMd): string {
  const lines: string[] = [];
  lines.push('# Migrated from CLAUDE.md');
  lines.push('# Generated by @claude-flow/codex');
  lines.push('');

  // Model
  lines.push(`model = "${parsed.settings.model || 'gpt-5.3-codex'}"`);
  lines.push('');

  // Approval policy
  const approvalPolicy = parsed.settings.approvalPolicy || 'on-request';
  lines.push(`approval_policy = "${approvalPolicy}"`);
  lines.push('');

  // Sandbox mode
  const sandboxMode = parsed.settings.sandboxMode || 'workspace-write';
  lines.push(`sandbox_mode = "${sandboxMode}"`);
  lines.push('');

  // Web search
  lines.push('web_search = "cached"');
  lines.push('');

  // Features
  lines.push('[features]');
  lines.push('child_agents_md = true');
  lines.push('shell_snapshot = true');
  lines.push('request_rule = true');
  lines.push('');

  // MCP servers
  if (parsed.mcpServers.length > 0) {
    for (const server of parsed.mcpServers) {
      lines.push(`[mcp_servers.${server.name.replace(/-/g, '_')}]`);
      lines.push(`command = "${server.command}"`);
      if (server.args && server.args.length > 0) {
        const argsStr = server.args.map((a) => `"${a}"`).join(', ');
        lines.push(`args = [${argsStr}]`);
      }
      lines.push(`enabled = ${server.enabled ?? true}`);
      lines.push('');
    }
  } else {
    // Default claude-flow server
    lines.push('[mcp_servers.ruflo]');
    lines.push('command = "npx"');
    lines.push('args = ["-y", "ruflo@latest", "mcp", "start"]');
    lines.push('enabled = true');
    lines.push('');
  }

  // Skills
  if (parsed.skills.length > 0) {
    lines.push('# Skills detected in original configuration');
    for (const skill of parsed.skills) {
      lines.push(`# - ${skill.name} (${skill.syntax} syntax)`);
    }
    lines.push('');
  }

  // History
  lines.push('[history]');
  lines.push('persistence = "save-all"');
  lines.push('');

  // Profiles
  lines.push('[profiles.dev]');
  lines.push('approval_policy = "never"');
  lines.push('sandbox_mode = "danger-full-access"');
  lines.push('');

  lines.push('[profiles.safe]');
  lines.push('approval_policy = "untrusted"');
  lines.push('sandbox_mode = "read-only"');
  lines.push('');

  return lines.join('\n');
}

/**
 * Migrate from Claude Code (CLAUDE.md) to Codex (AGENTS.md)
 */
